runtime: python312

entrypoint: gunicorn --bind :$PORT production_server:app --worker-class uvicorn.workers.UvicornWorker --timeout 0

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 3
  min_idle_instances: 0
  max_idle_instances: 1

env_variables:
  PYTHONUNBUFFERED: "1"
